### ISSUE TITLE
[MAC] Error: connect ECONNREFUSED 127.0.0.1:8090

### ISSUE THREAD

**Issue by Chris-Graffagnino** [input-output-hk/daedalus#650] opened 2018-01-08 03:21 UTC
Using Daedalus 1.0.3619
High Sierra 10.13.2

Last message from Daedalus.log `connect ECONNREFUSED 127.0.0.1:8090`

Last message from cardano-node.log `Locked by 400: resource busy`

**Comment by erikd** [comment] 2018-01-08 03:31
I think this is a dupe of #608 . I don't think this is just related to Linux.

If you agree this is a dupe, you should close this. Otherwise you should document why you think this is different.

**Closed** 2018-01-09 04:40 UTC
