### ISSUE TITLE
Windows Appdata storage but C drive full

### ISSUE THREAD

**Issue by sebsonf** [input-output-hk/daedalus#2329] opened 2021-02-02 07:08 UTC
Hi, please add an option to let the user choose where to store the blockchain. In my case C:\ drive was almost full and I did install Daedalus on D:\ drive. But it still synced the blockchain to C:\AppData until it froze with an error that the drive is full. I was not even able to change the location in the settings menu, as it did not open.

![image](https://user-images.githubusercontent.com/12183460/106564547-a6b8e180-652d-11eb-986d-fbce31277026.png)

**Comment by nikolaglumac** [comment] 2021-02-02 08:26
This is a duplicate of: https://github.com/input-output-hk/daedalus/issues/605

This feature is not yet implemented, but what I suggest you to do is:

1. Close Daedalus
2. Open the state directory: [Instructions](https://iohk.zendesk.com/hc/en-us/articles/360039391494-Open-the-state-directory)
3. Copy the "chain" directory to a different drive
4. Create a shortcut with the same name "chain" to that new location and place it in the state directory (where "chain" directory was previously)
5. Run Daedalus

This will free your C drive significantly since the "chain" directory makes 90% of state directory size.

**Closed by nikolaglumac** 2021-02-02 08:26 UTC

**Comment by sebsonf** [comment] 2021-02-13 13:58
I just tried it but it does not work on Windows, simply creates a new folder and ignores the shortcut with the same name

![image](https://user-images.githubusercontent.com/12183460/107851656-dd370c00-6e0b-11eb-81f8-0eda1041b677.png)

**Comment by nikolaglumac** [comment] 2021-02-13 14:21
@sebsonf are you sure you tried these exact steps **while Daedalus is closed**: https://github.com/input-output-hk/daedalus/issues/605#issuecomment-771782614

**Comment by sebsonf** [comment] 2021-02-13 14:34
Sorry my bad, using symbolic link instead of shortcut solved the issue! Thank you very much!
