### ISSUE TITLE
Support Export of xPub Key

### ISSUE THREAD

**Issue by michaeljfazio** [input-output-hk/daedalus#2345] opened 2021-02-06 16:32 UTC
It's tax time soon and I'd love it if I could use my normal tax tracking service so that I can get a consolidated view of what I need to pay the man. Problem is, they don't support xPub for Cardano and it seems this is because[ they claim the various Cardano wallets don't support easily extracting the xPub address](https://help.cointracker.io/en/articles/2645254-what-is-xpub-ypub-zpub-and-utxo). So, I'm forced to enter every wallet address manually, which kind of defeats the purpose of it all in the first place.....

It would be great if there were a convenient way to get the xPub address from the Daedalus UI similar to how you can do it in LedgerLive. I raised a ticket with CoinTracker.io referencing this issue in the hope that the addition of this feature may enable them to give their users a better portfolio/tax tracking experience.

**Comment by nikolaglumac** [comment] 2021-02-06 16:42
We have the UI for this feature already ready (implemented in https://github.com/input-output-hk/daedalus/pull/2271) and we will enable it as soon as we get the supporting API ready on the cardano-wallet side. 

Here's how it looks:
![101918428-32da0880-3b7e-11eb-9ab8-ccb5920f5ed8](https://user-images.githubusercontent.com/376611/107124190-96449600-68a2-11eb-81e6-adfe4bc94391.png)
![101918587-5f8e2000-3b7e-11eb-87e2-7f556e67911e](https://user-images.githubusercontent.com/376611/107124192-98a6f000-68a2-11eb-9fd0-e857cf4202b3.png)
![102502995-1e8d8400-4034-11eb-8e00-172881e2949c](https://user-images.githubusercontent.com/376611/107124194-993f8680-68a2-11eb-9f11-425533553e70.png)
![102782815-d1b8ee80-434e-11eb-861f-3ec450e045f4](https://user-images.githubusercontent.com/376611/107124195-99d81d00-68a2-11eb-8504-258ec6719f95.png)

**Comment by nikolaglumac** [comment] 2021-03-15 12:03
This feature has been implemented in https://github.com/input-output-hk/daedalus/pull/2429 and it is to be released on Daedalus Flight today. You can expect it on Daedalus Mainnet a bit later this week.
Thank you for the patience! 🙏

**Comment by nikolaglumac** [comment] 2021-03-30 18:25
This has been implemented and released in the scope of Daedalus Mainnet 4.0.3: https://github.com/input-output-hk/daedalus/releases/tag/4.0.3
Thanks for the patience 🙏

**Closed by nikolaglumac** 2021-03-30 18:25 UTC
Labels: :airplane: release-4.0.2-FC3, feature-request

**Comment by dgellow** [comment] 2021-03-31 07:24
@nikosbentenitis Should I be able to find my wallet on https://explorer.cardano.org/en.html by copy-pasting the public key? That's not the case for me, no result is found. I'm using a Ledger Nano S wallet, not sure if that matters here.

**Comment by nikolaglumac** [comment] 2021-03-31 12:28
@dgellow later on, new functionality will enable the import of read-only wallets from a wallet's public key. These view-only wallets will show the wallet's balance and transaction history without the ability to spend funds, change delegation preferences, or modify anything in the wallet. View-only wallets will be useful for auditing and similar purposes.

For now, I think you can only try importing the public key into services such as https://koinly.io/ or https://www.cointracker.io/

**Comment by dgellow** [comment] 2021-03-31 12:53
By curiosity I tried to import a wallet's public key with [Accointing](https://www.accointing.com/) but that doesn't seem to work. Of course that could be an issue on their side.

**Comment by nikolaglumac** [comment] 2021-03-31 12:55
They most likely do not have support for Cardano public keys yet.

**Comment by dgellow** [comment] 2021-03-31 13:03
Ok, I think that I understand. They do have support for "XPubKey" which is what you describe as "view-only wallet" as far as I understand.

**Comment by nikolaglumac** [comment] 2021-03-31 13:06
Indeed. Still, it is important to have the same implementation.

**Comment by dgellow** [comment] 2021-03-31 13:09
Thanks :)

**Comment by edwmurph** [comment] 2021-03-31 14:23
> For now, I think you can only try importing the public key into services such as https://koinly.io/ or https://www.cointracker.io/

i updated my daedalus to 4.0.3 but when i try to add the "Wallet public key" as a public address wallet to my cointracker, it's failing with "Failed to add wallet. Please check the values below." i also confirmed that cointracker isn't even able to fetch the balance via https://www.cointracker.io/wallet/cardano and is failing on that page with "Failed to fetch wallet balance". is this cointracker integration actually working for anyone?

**Comment by nikolaglumac** [comment] 2021-03-31 14:49
I believe https://www.cointracker.io/wallet/cardano accepts wallet address and not public account key.

**Comment by nikolaglumac** [comment] 2021-03-31 14:51
I can confirm it works if you paste in a valid wallet address:
![Screenshot 2021-03-31 at 16 51 34](https://user-images.githubusercontent.com/376611/113164438-65993100-9241-11eb-8ca5-f3030e19f63b.png)

**Comment by edwmurph** [comment] 2021-03-31 15:02
oh ya i've been able to manually put all the generated addresses for my daedalus wallet into my cointracker fine. i just currently dont see a way to import this new daedalus wallet public key into cointracker? it sounds like cointracker actually doesn't support importing cardano public keys yet

this is a pain point for me because i had to manually import all my generated addresses for my daedalus wallet into cointracker for taxes so im looking forward to the day when i can just give cointracker the one public key for my wallet

**Comment by nikolaglumac** [comment] 2021-03-31 15:15
Sorry for that...
I believe now the cointracker needs to be updated to handle import of the Cardano wallet account public keys.

**Comment by michaeljfazio** [comment] 2021-03-31 22:31
> oh ya i've been able to manually put all the generated addresses for my daedalus wallet into my cointracker fine. i just currently dont see a way to import this new daedalus wallet public key into cointracker? it sounds like cointracker actually doesn't support importing cardano public keys yet
> 
> this is a pain point for me because i had to manually import all my generated addresses for my daedalus wallet into cointracker for taxes so im looking forward to the day when i can just give cointracker the one public key for my wallet

This is correct. I’ve raised this with CoinTracker multiple times now. I suggest you lodge a support request with then and reference this issue so we can generate some visibility with them. Unfortunately they’re support is atrocious when it comes to this type of thing.

**Comment by edwmurph** [comment] 2021-04-05 14:55
added a feature request to cointracker if anyone wants to upvote it to help get cointracker's attention on this https://feedback.cointracker.io/features/p/add-support-for-importing-transactions-via-xpub-cardano-daedalus-keys

**Comment by airtonix** [comment] 2021-04-17 06:17
> oh ya i've been able to manually put all the generated addresses for my daedalus wallet into my cointracker fine. i just currently dont see a way to import this new daedalus wallet public key into cointracker? it sounds like cointracker actually doesn't support importing cardano public keys yet
> 
> this is a pain point for me because i had to manually import all my generated addresses for my daedalus wallet into cointracker for taxes so im looking forward to the day when i can just give cointracker the one public key for my wallet

@edwmurph  how? adding a hd ledger wallet only lets you put one address.

**Comment by edwmurph** [comment] 2021-04-17 17:22
i added a new/separate public address wallet to cointracker for each of the generated addresses for my daedalus wallet into cointracker via https://www.cointracker.io/add_wallet

![image](https://user-images.githubusercontent.com/20996513/115121280-bc13a880-9f7f-11eb-958d-265b694f9125.png)

**Comment by pedrocanelas** [comment] 2021-06-05 21:41
I'm so happy I found this post! Today I found Accounting and it is the first tracker that I managed to sync with Daedalus. I'm just wondering if is possible to see my ADA that was delegated. Are there extra settings or flow for it or I'm asking something impossible?

**Comment by nikolaglumac** [comment] 2021-06-07 08:22
Not sure what you mean by "ada that was delegated"?

**Comment by pedrocanelas** [comment] 2021-06-07 08:35
When I stake my ADA delegating to a Pool, I can't see it anymore. It makes sense because it left my wallet and now is in the pool but I'm wondering if there is still a way of tracking using some Portfolio tracker like Accointing. For now, I managed to solve adding manually the amount of ADA that I have, I think this should be enough.

**Comment by nikolaglumac** [comment] 2021-06-07 09:40
Ada that you delegate never leaves Daedalus so I am still not sure what you mean.

**Comment by pedrocanelas** [comment] 2021-06-07 09:48
I opened Daedalus, went to Settings, copied my wallet address and I pasted it to connect to Accointing. On Accointing it shows I have 0 ADA. I assumed that happens because all my ADA is delegated. So what you are saying is that I should be able to still see, right?

**Comment by nikolaglumac** [comment] 2021-06-07 09:51
What is the balance of the wallet shown in Daedalus?

**Comment by pedrocanelas** [comment] 2021-06-07 11:09
On Daedalus, I can see my balance correctly. When I try to add a Cardano Wallet on Accounting and I enter the public key address found on Settings, Accointing shows I have nothing. Now reading again the thread, I see it should be an issue from Accointing side and the lack of possibility of reading the Public Key. 😕

**Comment by nikolaglumac** [comment] 2021-06-07 11:24
Yes this sounds like an issue on their end :-(

**Comment by pedrocanelas** [comment] 2021-06-07 11:26
Cointracker offers the option to add a wallet via Public Key but when I paste it, it says "Failed to add wallet. Please check the values below.". I will check with them. Thank you so much for the quick replies! :)

**Comment by cecarlsen** [comment] 2024-04-07 16:46
I'm trying to track for tax using Koinly, and it seems they only support xpub keys, not the Cardano public key. As far as I can se, there is no easy way to export such a key from Daedalus. If anyone has a solution, please share.
