### ISSUE TITLE
Windows 10: Loop "crashing" startup issue, with 'Unexpected end of JSON input' error in logs

### ISSUE THREAD

**Issue by praseenr** [input-output-hk/daedalus#2750] opened 2021-11-19 16:24 UTC
Hi Daedalus developers/support,
Since my Daedalus wallet was automatically upgraded to Cardano Wallet 2021.9.29 (Windows build 19689, Cardano Node 1.30.1) version, on 11/18/2021... my Daedalus wallet started crashing. And when I checked the logs at developer tools, i see below error:

 DevTools failed to load source map: Could not parse content for file:///**<my-daedalus-wallet-folder-path>**/preload.js.map: Unexpected end of JSON input.

Request to help me address the above post upgrade issue of Daedalus wallet. 

Thanks in advance.

**Comment by CherryDT** [comment] 2021-11-19 21:46
This may be a red herring, look at `%appdata%\Daedalus Mainnet\Logs\pub\node.log` and see if there are errors at the bottom. If you see `DbLocked` errors then it's a duplicate of #2746, and you can find a workaround there (and the tram is working on a fix).

**Comment by nikolaglumac** [comment] 2021-11-22 11:26
Hi!
This issue should be fixed in the latest release 4.5.1.
Can you please see if it works?
Thanks!

**Comment by dmitrii-gaico** [comment] 2021-11-29 11:56
@praseenr Hello. Could you please confirm if you are no longer experiencing the issue in the latest 4.5.2 release ?
Thank you in advance!

**Comment by dmitrii-gaico** [comment] 2021-12-06 09:38
Closing the call due to the issue was fixed in 4.5.2 release.
If you still facing the crashing loop please create a new card with a reference to the actual one.
Thank you.

**Closed by dmitrii-gaico** 2021-12-06 09:38 UTC
Labels: bug
