### ISSUE TITLE
Rewards cannot be sent/withdrawn 

### ISSUE THREAD

**Issue by Klobbinger** [input-output-hk/daedalus#2274] opened 2020-12-12 14:29 UTC
It seems like rewards cannot be transferred to another address in the 3.0.0 versions of Daedalus and Flight. The wallet only allows to transfer the utxo balances, not the funds on the rewards account.

**Comment by nikolaglumac** [comment] 2020-12-14 09:07
@Klobbinger can you please share more details? Rewards are for sure transferable - I have just confirmed that by running the test on my own. Couple of things you should bare in mind:
1. Wallet rewards are included in the wallet balance shown on the "Summary" screen and in the sidebar/topbar
2. Rewards shown on the "Rewards" screen are cumulative historical rewards your wallet received and NOT the current wallet rewards balance
3. If your wallet balance is zero it means you have actually withdrawn all the rewards as well as your UTXO balance.

**Comment by Klobbinger** [comment] 2020-12-14 10:03
@nikolaglumac Yes, I'm aware of the points you describe. I do have a balance left in my wallet. When I try to send it, I get the error message. There is definitely enough UTXO balance left to pay for the transaction fees. I also doublechecked this in Yoroi, which shows me both balances separately . 

![grafik](https://user-images.githubusercontent.com/67224145/102067790-e865bf80-3dfb-11eb-8c96-af51747a636f.png)

**Comment by nikolaglumac** [comment] 2020-12-14 10:13
@Klobbinger it looks like 1000 is the full balance of your wallet. That won't work as you also have to pay fees. Try sending a smaller amount.

**Comment by Klobbinger** [comment] 2020-12-14 10:16
@nikolaglumac no, my full balance is higher. It will allow transaction for the exact part of the total balance that is on utxo Adress. As soon as the threshold is passed so that the wallet would need to include funds from the rewards account, I get the error message.

**Comment by Klobbinger** [comment] 2020-12-14 10:54
@nikolaglumac 
This works because UTXO balance is greater than 200

![grafik](https://user-images.githubusercontent.com/67224145/102072813-af7d1900-3e02-11eb-9627-eb8a39eb1e81.png)

This doesn't, because UTXO Balance is smaller than 400, but total balance including rewards is greater than 1000.

![grafik](https://user-images.githubusercontent.com/67224145/102072897-c6bc0680-3e02-11eb-9e44-596632f08a5e.png)

**Comment by nikolaglumac** [comment] 2020-12-14 11:39
@Klobbinger how do you know which part of your wallet balance is UTXO and which is rewards?

**Comment by Klobbinger** [comment] 2020-12-14 12:00
@nikolaglumac
2 ways:
1. Prior to my last transaction, I did not move any funds in this wallet that I have also been staking. So since the rewards shown in the delegation center are exactly the amount of my total balance that I cannot send, it's clear that it's in the rewards account.
2. I have the same wallet restored in Yoroi which shows those two balances separately. Here I have the option to manually "withdraw" the rewards.

If it helps finding the root cause, I could withdraw in Yoroi and check if that made the total wallet balance sendable in daedalus.

**Comment by nikolaglumac** [comment] 2020-12-14 12:54
This is indeed strange... Daedalus uses rewards balance if there are any rewards. The code looks good so if this is a bug it is something on the cardano-wallet side. @KtorZ please help us out here 🙏

**Comment by nikolaglumac** [comment] 2020-12-14 12:59
@gnpf @ManusMcCole @mioriohk please try to reproduce this issue and let us know the results 🙏  Thanks!

**Comment by KtorZ** [comment] 2020-12-14 13:49
I don't know how much are the rewards, but cardano-wallet will not withdraw rewards if rewards don't bring as much value as what they cost. Indeed, withdrawing from a reward account increases the size of a transaction and the resulting fees. If the rewards are too small, it may not be worth withdrawing them yet. cardano-wallet will therefore only consider rewards if they are big enough. Could it be the case that rewards are indeed quite small?

**Comment by Klobbinger** [comment] 2020-12-14 13:52
@KtorZ in my case the rewards are well above that threshold so that can't be the reason.

**Comment by Klobbinger** [comment] 2020-12-14 13:57
Also, another user who confirmed to have the same problem like me uses a hardware wallet account. So the issue might be related to the he wallet feature.

**Comment by nikolaglumac** [comment] 2020-12-14 14:04
@tomothespian @KtorZ can you please look into this? 🙏

**Comment by nikolaglumac** [comment] 2020-12-14 14:38
@Klobbinger we will look into this. Thank you for reporting and thanks for patience!

**Comment by Klobbinger** [comment] 2020-12-14 14:44
Happy to help! I'd like to see myself more like a member of the team than a customer ;) you guys are doing a great job!

**Comment by Klobbinger** [comment] 2021-01-05 18:10
In Daedalus and Flight 3.1.0 the problem persists. It only affects hardware wallets, not regular wallets.

**Comment by nikolaglumac** [comment] 2021-01-05 22:35
> In Daedalus and Flight 3.1.0 the problem persists. It only affects hardware wallets, not regular wallets.

Unfortunately, the problem has not been resolved yet. Sorry for the inconvenience and thanks for the patience! I hope we will get the fix into the next Daedalus release 🙏

**Comment by nikolaglumac** [comment] 2021-01-12 09:49
This issue needs to first be fixed on the cardano-wallet side: https://github.com/input-output-hk/cardano-wallet/issues/2440
As soon as the fix is ready we will adjust the code on our side and release it.

**Comment by EtherDotBlue** [comment] 2021-02-26 03:32
@nikolaglumac I confirmed that this issue has not been resolved in the latest release.  Do you have an ETA? I have a significant amount stuck.

**Comment by wadie914** [comment] 2021-02-26 03:33
I have a pretty significant amount myself

**Comment by wadie914** [comment] 2021-02-26 03:35
I even tried the Mac version but it will not connect in order for me to use
the key tool

**Comment by nikolaglumac** [comment] 2021-02-26 07:35
> @nikolaglumac I confirmed that this issue has not been resolved in the latest release. Do you have an ETA? I have a significant amount stuck.

@EtherDotBlue we would have had announced this as fixed if it was the case.
There is an open PR that adds the support for withdrawals on hardware wallets: https://github.com/input-output-hk/daedalus/pull/2408
Once merged, we will have it released (first on Daedalus Flight and shortly after on Daedalus Mainnet).
I expect this to happen in the next 2 weeks.

Thanks for the patience!

**Comment by nikolaglumac** [comment] 2021-03-02 10:03
The fix for this issue is now available in Daedalus Flight 4.0.0-FC1: https://daedaluswallet.io/en/flight/
We will be releasing it on Daedalus Mainnet next week.
Thank you for the patience!

**Comment by Klobbinger** [comment] 2021-03-02 10:09
Thanks for your hard and relentless work! Haven't tried the fix yet but trust it'll work!

**Comment by nikolaglumac** [comment] 2021-03-02 10:16
@Klobbinger please let us know if it worked! Thanks 😃

**Comment by wadie914** [comment] 2021-03-02 13:51
I tried to import the secret key it did not load up

**Comment by Klobbinger** [comment] 2021-03-03 12:01
@nikolaglumac

Just tested, it works 👍 
I noticed the following :
The wallet wants to withdraw the rewards from the account even if the utxo balance is sufficient for the transaction. I'm not sure this is the intended design.

**Comment by KtorZ** [comment] 2021-03-03 12:12
@Klobbinger it is. The wallet will withdraw rewards as soon as they are "worth it" (that is, withdrawing them doesn't cost you more than what they're worth). In principle, as a user you have:

a) no reasons to even know about it 
b) no reasons to keep your rewards in a reward account. 

When withdrawing, delegation choices are preserved so it is really a transparent operation. Also good to know, the wallet favor rewards to pay for fees, so that it doesn't have to move existing UTxO around.

**Comment by Klobbinger** [comment] 2021-03-03 12:35
@KtorZ it's my understanding that fees cannot be payed from the rewards. That's one of the downsides when switching to a new wallet. You'll need to leave some Ada in the old wallet so you can withdraw the rewards that will come with a delay and since they are automatically redelegated you'll have to withdraw them to a new wallet after every epoch until they are negligible.

The way it worked for me was the following:
100 Ada in utxo, 10 Ada in rewards account. 
Send 1 Ada. The wallet will withdraw all 10 Ada and pay transaction fee from utxo.
Without a hardware wallet the user probably wouldn't notice, but the hardware wallet explicitly tells me that it's withdrawing rewards from account.

Anyway, those are just my observations, thought it might be helpful.

The issue itself is fixed, thanks again to everyone involved!

**Comment by nikolaglumac** [comment] 2021-03-03 13:49
Perfect! Thanks for letting us know!
I will close this ticker as soon as we release Daedalus Mainnet 4.0.0.

**Comment by nikolaglumac** [comment] 2021-03-30 18:26
This has been implemented and released in the scope of Daedalus Mainnet 4.0.3: https://github.com/input-output-hk/daedalus/releases/tag/4.0.3
Thanks for the patience! 🙏

**Closed by nikolaglumac** 2021-03-30 18:26 UTC
Labels: :airplane: release-4.0.0-FC1, bug, release-4.0.0, release-4.0.0-RC1

**Comment by wadie914** [comment] 2021-03-30 18:36
Fixed?

**Comment by nikolaglumac** [comment] 2021-03-30 18:38
@wadie914 if you are asking about wallet import feature, then I must disappoint you as it has not yet been fixed. The good news is we have an open PR which might fix the issue: https://github.com/input-output-hk/daedalus/pull/2445
Will keep you posted on the original thread. Thanks for the patience!

**Comment by wadie914** [comment] 2021-03-30 18:41
Thank you man
