### ISSUE TITLE
State directory can not be configured and is set to default drive

### ISSUE THREAD

**Issue by Ahmedie-m** [input-output-hk/daedalus#2391] opened 2021-02-21 07:25 UTC
When trying to install Daedalus wallet, I selected for it to be installed on the D drive. That worked fine, but the state directory was still pushed to the C drive.

I would recommend this to be configurable in the installer, as there were no options there for this and I can't seem to find a way to change the drive and right now it's just stuck on this screen:

![image](https://user-images.githubusercontent.com/61509242/108618423-b342a280-7426-11eb-948a-d2d40f236728.png)

**Comment by nikolaglumac** [comment] 2021-02-21 09:06
Duplicate of https://github.com/input-output-hk/daedalus/issues/605
Please follow this: https://github.com/input-output-hk/daedalus/issues/605#issuecomment-771782614

**Closed by nikolaglumac** 2021-02-21 09:06 UTC
