### ISSUE TITLE
Block store

### ISSUE THREAD

**Issue by noescape00** [input-output-hk/daedalus#576] opened 2017-12-04 22:39 UTC
Please don't store each block separately in 1kb files. 
It takes forever to copy\remove\move daedalus folder even on SSD. Plus it takes 3 times more disk space just for the file system metadata than the actual block's size. 

I can't imagine DB performance issues daedalus is facing with that approach. 
Really hope it will be fixed in next updates of this awesome wallet.

**Comment by cleverca22** [comment] 2017-12-04 22:40
i also recently discovered this problem, it took half an hour just to uninstall daedalus while testing things

**Comment by csoroz** [comment] 2018-01-03 01:56
About waste of disk space., currently in my directory blocks/data:

Contains: 874002 files, 256 folders
Size: 391 MB
Size on disk: 1.69 GB !!!!!

**Comment by cleverca22** [comment] 2018-01-03 03:03
on my ZFS/linux machine, its taking up 2.8gig!

**Comment by erikd** [comment] 2018-01-03 04:43
I'm pretty sure this has nothing to do with the daedalus wallet and everything to do with the `cardano-node` executable that is in the https://github.com/input-output-hk/cardano-sl repository.

**Comment by erikd** [comment] 2018-01-06 10:20
Cardano creates a *lot* of very small in disk:
```
> find  Daedalus/DB-1.0/blocks/data/ -type f | wc -l
902962
```
and that number is constantly growing.

Compare this to Bitcoin core which has a blockchain dating back to 2009 and does so with a little more that 4000 files.

**Comment by gwpl** [comment] 2018-01-23 21:29
Btw. shouldn't this "block store feature request" be under cardano-sl project?

**Comment by nikolaglumac** [comment] 2019-01-30 11:02
Duplicate of: https://github.com/input-output-hk/daedalus/issues/605

**Closed by nikolaglumac** 2019-01-30 11:02 UTC

**Comment by ejpcmac** [comment] 2019-01-30 15:31
@nikolaglumac I’m not sure this is a duplicate: #605 deals with the blocks storage location, this one with the block format.

**Comment by nikolaglumac** [comment] 2019-01-30 16:02
In that case please post your question in the following repo: 
https://github.com/input-output-hk/cardano-sl
