### ISSUE TITLE
Fully nixified build

### ISSUE THREAD

**Issue by taktoa** [input-output-hk/daedalus#492] opened 2017-09-21 01:16 UTC
Ideally this would have a fully reproducible build using Nix and a pinned nixpkgs. I recommend checking out [nixfromnpm](https://github.com/adnelson/nixfromnpm) for getting NodeJS related stuff to work.

**Comment by domenkozar** [comment] 2017-09-21 18:57
Hey @taktoa - is that better than yarn2nix? We never attempted to package node stuff in Nix. Feels quite broken.

**Comment by taktoa** [comment] 2017-09-22 03:08
I hadn't heard about yarn2nix, so I can't express an informed opinion on the subject, but nixfromnpm has the advantage of avoiding building the same package twice, which seems to happen a lot with npm2nix and node2nix.

**Comment by domenkozar** [comment] 2017-09-27 13:53
Thanks - we will look into it.

**Comment by ixmatus** [comment] 2017-12-11 06:05
I would like to see this too. I've tried nixifying the Wire app and Signal Desktop apps before with `nixfromnpm` and it didn't fair well there (each for different reasons). I tried nixifying Daedalus with `nixfromnpm` but ran into these errors with a checkout of `master`:

```
...
Failed to generate expressions for 4 downstream dependencies.
  web3-requestManager@>=1.1.0 <2.0.0
   Dependency of:
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-bzz@1.1.0 -> web3-core@1.1.0
Failed to build because: NoMatchingPackage web3-requestManager
  web3-core-promiEvent@>=1.1.0 <2.0.0
   Dependency of:
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-eth@1.1.0 -> web3-eth-contract@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-bzz@1.1.0 -> web3-core-method@1.1.0
Failed to build because: NoMatchingPackage web3-core-promiEvent
  web3-net@>=1.1.0 <2.0.0
   Dependency of:
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-bzz@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-eth@1.1.0 -> web3-eth-personal@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-eth@1.1.0
Failed to build because: NoMatchingVersion >=1.1.0 <2.0.0
  web3-utils@>=1.1.0 <2.0.0
   Dependency of:
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-bzz@1.1.0 -> web3-core-method@1.1.0 -> web3-core-helpers@1.1.0 -> web3-eth-iban@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-bzz@1.1.0 -> web3-core-method@1.1.0 -> web3-core-helpers@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-eth@1.1.0 -> web3-eth-personal@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-eth@1.1.0 -> web3-eth-contract@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-eth@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-bzz@1.1.0 -> web3-core-method@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-eth@1.1.0 -> web3-eth-abi@1.1.0
    daedalus@0.8.0 -> web3@1.0.0-beta.24 -> web3-bzz@1.1.0 -> web3-core@1.1.0
Failed to build because: NoMatchingVersion >=1.1.0 <2.0.0
```

I'm just going to resort to elf patching for the time being.

**Comment by ixmatus** [comment] 2017-12-11 06:08
My experience with `yarn2nix` isn't bad but I think `nixfromnpm` does more for you (i.e. you don't have to rely on a generated yarn lock file and it will go deeper into the dev dependencies, which are often required to build).

**Comment by ixmatus** [comment] 2017-12-11 06:10
I've successfully built a complex node app with `nixfromnpm` after some effort. The nice thing about `nixfromnpm` is that every generated npm package can be overridden, it's painful to do because the npm package set isn't defined as a fixpoint, but it's possible to override packages without mucking with the generated code.

**Comment by jluttine** [comment] 2017-12-15 19:46
I think I got the same error about no matching version, but I got it solved by checking out the latest tag 0.8.0 instead of building from master. Not sure if it helps you though.

**Comment by ixmatus** [comment] 2017-12-15 19:50
@jluttine were you able to build with `nixfromnpm` without modifying its generated code? And yeah, I probably should have been building against the tag... Perhaps this weekend I'll give it another go unless you've beaten me to it ;)

**Comment by taktoa** [comment] 2017-12-15 21:15
A few weeks ago I tried using `yarn2nix` to build daedalus, but ran into an issue where yarn2nix wouldn't correctly handle `git+https://...` URLs in the `yarn.lock` file. I forked `yarn2nix` and made a [branch][] (commit [permalink][]) that I think should fix the problem, but I don't have time to test it right now.

cc @moretea

[branch]: https://github.com/taktoa/yarn2nix/tree/taktoa/fetchgit
[permalink]: https://github.com/taktoa/yarn2nix/commit/7ee45f753fda3eef5d8101bc9088f3e654f7f1ae

**Comment by jluttine** [comment] 2017-12-16 15:21
(Copied from https://github.com/NixOS/nixpkgs/issues/32516#issuecomment-352179607)

I also tried with `yarn2nix` now. I modified the `yarn.lock` file a little bit to replace `git+https` with `https`. The derivation expression:
```
{lib, pkgs, ...}:
with (import /home/jluttine/Workspace/yarn2nix { inherit pkgs; });
mkYarnPackage rec {
  name = "${pname}-${version}";
  pname = "daedalus";
  version = "0.8.0";
  src = /home/jluttine/Workspace/daedalus;
  packageJson = /home/jluttine/Workspace/daedalus/package.json;
  yarnLock = /home/jluttine/Workspace/daedalus/yarn.lock;
}
```

Modified yarn.lock file: https://gist.github.com/jluttine/a577e815d17fc2ae71344c820986fb32

However, I get the following error:
```
[1/4] Resolving packages...
error Couldn't find any versions for "aes-js" that matches "2.1.1" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
```

It seems that the packages aren't found for some reason. I also asked on yarn2nix repo about this: https://github.com/moretea/yarn2nix/issues/49

Any ideas?

**Comment by taktoa** [comment] 2017-12-16 15:21
@jluttine did you try my modified version of `yarn2nix`?

**Comment by jluttine** [comment] 2017-12-16 15:30
@taktoa Tried now and got the following error:

```
building path(s) ‘/nix/store/lq9k8hyjxjjq1s30c5hkb4ydad0p8dr3-yarn2nix-modules-0.1.0’
building
yarn config v1.3.2
success Set "yarn-offline-mirror" to "/nix/store/q40krfwq0ny0s6d6shfzrqwhbic2zdy8-offline".
Done in 0.10s.
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
Done in 0.20s.
patching script interpreter paths in /nix/store/lq9k8hyjxjjq1s30c5hkb4ydad0p8dr3-yarn2nix-modules-0.1.0
building path(s) ‘/nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0’
unpacking sources
unpacking source archive /nix/store/hcvm7qqnmvqxf7cykznnj02y8f630z9l-yarn2nix
source root is yarn2nix
patching sources
configuring
building
no Makefile, doing nothing
installing
Processing  yarn2nix
Linked yarn2nix
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0
stripping (with flags -S) in /nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0/bin 
patching script interpreter paths in /nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0
/nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0/node_modules/yarn2nix/bin/yarn2nix.js: interpreter directive changed from "/usr/bin/env node" to "/nix/store/b86jma2mb5d0805p0kkk20g4ppqjvda7-nodejs-6.11.5/bin/node"
checking for references to /tmp/nix-build-yarn2nix-0.1.0.drv-0 in /nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0...
building path(s) ‘/nix/store/wzpxhsc9dhwdccp3rsg34kg2lnzyyrk9-yarn.nix’
child_process.js:515
    throw err;
    ^

Error: Command failed: /nix/store/wmbgbcglgccpqkn189fsn7fk1zg4irvf-nix-prefetch-git/bin/nix-prefetch-git https://github.com/enlight/node-inspector accd46758501d8187e55b32b54e3eff65c3fdaa3
    at checkExecSyncError (child_process.js:472:13)
    at Object.execSync (child_process.js:512:13)
    at generateNix (/nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0/node_modules/yarn2nix/bin/yarn2nix.js:65:50)
    at Object.<anonymous> (/nix/store/hbns745d0arprqql4zmjwqg499w8089s-yarn2nix-0.1.0/node_modules/yarn2nix/bin/yarn2nix.js:107:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
builder for ‘/nix/store/z0vx89bf7rwkjhflz8lan3fgd8jb211l-yarn.nix.drv’ failed with exit code 1
error: build of ‘/nix/store/z0vx89bf7rwkjhflz8lan3fgd8jb211l-yarn.nix.drv’ failed
(use ‘--show-trace’ to show detailed location information)
```

If I understood correctly, that `yarn2nix` fails to build?

**Comment by cleverca22** [comment] 2017-12-16 15:31
@jluttine i think nix-prefetch-git has to be added to the buildInputs of the derivation building `yarn.nix`

**Comment by taktoa** [comment] 2017-12-16 15:32
no, `yarn2nix` successfully built, it's just that to support `git+https` URLs I had to make it invoke `nix-prefetch-git`, which obviously cannot be done in a non-fixed-output derivation under the nix sandbox
the solution is to run the `yarn2nix` binary outside, then add it to the arguments of `mkYarnPackage`.

**Comment by jluttine** [comment] 2017-12-16 15:44
@taktoa WIth this patch to your branch, it worked with git+https:

```
diff --git a/default.nix b/default.nix
index f8f3300..6020c90 100644
--- a/default.nix
+++ b/default.nix
@@ -4,7 +4,7 @@
 }:
 
 let
-  inherit (pkgs) stdenv lib fetchurl linkFarm;
+  inherit (pkgs) stdenv lib fetchurl linkFarm fetchgit;
 in rec {
   # Export yarn again to make it easier to find out which yarn was used.
   inherit yarn;
@@ -21,7 +21,7 @@ in rec {
   # the package source.
   importOfflineCache = yarnNix:
     let
-      pkg = import yarnNix { inherit fetchurl linkFarm; };
+      pkg = import yarnNix { inherit fetchurl linkFarm fetchgit; };
     in
       pkg.offline_cache;
```

But it still didn't build Daedalus. It ended with the same error I reported above with the modified `yarn.lock` file:
```
[1/4] Resolving packages...
error Couldn't find any versions for "aes-js" that matches "2.1.1" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
```
To me it sounds like it's not finding the packages for some reason. I'm quite lost here.

**Comment by domenkozar** [comment] 2017-12-18 13:57
@jluttine it might be worth getting a reproducable test case and file an issue to https://github.com/moretea/yarn2nix

**Comment by kfiresmith** [comment] 2018-02-14 15:01
Since the more end-user focused ticket (#631) got merged into this ticket, I wanted to reach out (again, as an end-user of Daedalus) and mention that regardless of what happens with NPM packaging, the best current user-focused distribution option is likely to be an AppImage which bundles everything up and makes any understanding of the underlying language and language environment setup not required.

  It's also distribution agnostic so it's a lot easier for the developers to keep current as compared to publishing RPMs and Debs:  https://appimage.org/

**Comment by domenkozar** [comment] 2018-02-14 15:26
Thanks for the feedback. We know about prior art (nix-bundle, appimage, flatpak, etc) and we'll definitely pick one of them to start with - which ever turns out best.

**Comment by domenkozar** [comment] 2018-04-17 12:17
@Profpatsch 

It's fully nixified and uses:

- stack2nix for haskell part in https://github.com/input-output-hk/cardano-sl/tree/develop/pkgs
- yarn2nix for frontend in https://github.com/input-output-hk/daedalus/blob/develop/yarn2nix.nix
- nix-bundle for gluing it all together in https://github.com/input-output-hk/daedalus/blob/develop/default.nix

**Comment by deepfire** [comment] 2018-04-17 13:59
And our hero is @cleverca22!

**Comment by probonopd** [comment] 2018-11-25 20:38
What is holding you back from publishing an AppImage?

**Comment by jluttine** [comment] 2019-01-19 17:09
Would love to see Daedalus in nixpkgs! Then it could be installed easily. As the dev team uses nix, I would have expected that they would have added it there too, but is there some particular reason why this has not been done or just lack of time and prioritization? I once tried to add it to nixpkgs but after spending many days and countless hours on it, I gave up. I believe the dev team would know how to write the derivation into nixpkgs.

**Comment by nikolaglumac** [comment] 2019-01-30 12:18
@cleverca22 @rvl @deepfire any input from your side guys is much appreciated here!

**Comment by nikolaglumac** [comment] 2019-08-14 08:50
@cleverca22 can you please comment on this one 🙏

**Comment by nikolaglumac** [comment] 2020-05-06 20:06
Daedalus build is now fully "nixified". Please follow steps from Daedalus README: https://github.com/input-output-hk/daedalus/blob/develop/README.md#nix

**Closed by nikolaglumac** 2020-05-06 20:06 UTC
Labels: question

**Comment by locallycompact** [comment] 2021-11-14 20:29
Can I please reopen this issue? I do not see the claim that this build is fully nixified to be reflected in the README. I see derivations that produce installers, but I do not see any derivation that simply runs the wallet.

**Comment by rvl** [comment] 2021-11-15 03:48
Hi @locallycompact, please open a new issue with a good explanation of what you need and why.
I suspect that you want to be able to start Daedalus with something like `nix run github:input-output-hk/daedalus#electronApp`, right?

**Comment by locallycompact** [comment] 2021-11-15 10:09
Ok, yes I want something that would be suitable to consume in a system config.
