### ISSUE TITLE
Unplugging USB devices crashes wallet

### ISSUE THREAD

**Issue by Scalextrix** [input-output-hk/daedalus#2527] opened 2021-04-20 07:56 UTC
I switch my keyboard mouse between devices manually, if I do this while Daedalus is open it causes the wallet to crash about 5-10 seconds after I unplug the USB.

The node log shows nothing, its a silent crash.

OS: Windows 10
Daedalus 4.0.5

**Comment by nikolaglumac** [comment] 2021-04-20 08:03
Closing as it is a duplicate of https://github.com/input-output-hk/daedalus/issues/2519
@Scalextrix please add your report as a comment in the above-mentioned issue.
Thanks!

**Closed by nikolaglumac** 2021-04-20 08:03 UTC
