### ISSUE TITLE
Administrative privilege on OS X

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/daedalus#626] opened 2017-12-27 19:41 UTC
Does this wallet have to require an administrative privilege when being installed on OS X? It sounds quite unnecessary.

**Comment by pozyx** [comment] 2018-01-03 23:01
[Also on Windows](https://github.com/input-output-hk/daedalus/issues/644)

**Comment by erikd** [comment] 2018-01-04 02:13
I've compiled cardano/daedalus from source on Linux and it runs fine as a normal user.

**Comment by danunahui** [comment] 2018-05-15 04:43
It requires a password when being installed, distributed in .pkg and pin an app to the dock after installation. All this is very strange and not required for most other apps.
I do not know if the password is required after installation, because the installer fails for me every time, so I unpack the pkg > Payload and move Daedalus.app to the Applications folder.

**Comment by nikolaglumac** [comment] 2019-01-30 14:06
Duplicate of: https://github.com/input-output-hk/daedalus/issues/587

**Closed by nikolaglumac** 2019-01-30 14:06 UTC
