### ISSUE TITLE
NTP Check window hides "Stopping Cardano Node"

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/daedalus#1238] opened 2018-12-29 04:27 UTC
This is maybe a low-priority issue

### Preamble
In the latest release, closing Daedalus is not longer an instantaneous action. To let the user know the app is not frozen, "Stopping Cardano Node..." is rendered on the screen.

### Bug

If the user is presented with the NTP error screen and tries to close the application, it will not show "Stopping Cardano Node..." as the error screen takes priority. This gives the user the feeling the app is not responsive

**Comment by nikolaglumac** [comment] 2019-01-23 13:50
Thanks for the report @SebastienGllmt.
The issue is resolved in https://github.com/input-output-hk/daedalus/pull/1279 and will be released with Daedalus v0.13.0.

**Closed by nikolaglumac** 2019-01-23 13:50 UTC
