### ISSUE TITLE
UI/UX should show key deposit as part of delegation costs

### ISSUE THREAD

**Issue by jdloft** [input-output-hk/daedalus#2171] opened 2020-08-28 00:24 UTC
Similar to #2160

Alongside of the fees, UI should show that a 2 ADA deposit will be included in the cost to submit a delegation certificate.

![Screenshot from 2020-08-27 18-24-09](https://user-images.githubusercontent.com/8332322/91507640-86a43880-e892-11ea-98c9-483f590d26ab.png)

**Comment by nikolaglumac** [comment] 2021-02-03 13:49
This is to be added in soon.

**Comment by nikolaglumac** [comment] 2021-02-03 13:53
Closing this one as it is a duplicate of: https://github.com/input-output-hk/daedalus/issues/2116

**Closed by nikolaglumac** 2021-02-03 13:53 UTC
Labels: feature-request
