### ISSUE TITLE
FR: Changing the mainnet storage location within the GUI

### ISSUE THREAD

**Issue by danger89** [input-output-hk/daedalus#2662] opened 2021-09-07 22:01 UTC
As a user I would like to change the blockchain (mainnet) storage location to another directory. 

I expect those settings some where in the settings menu or wallet menu. Thus _without_ symlinks I want to be able to easily select another directory and/or disk where the data got stored on.

Please, these are important low-hanging fruit that needs to be solved, otherwise people will keep using adalite or yoroi wallets. I believe in Daedalus as the go-to wallet and easy to use.

Regards,
Melroy van den Berg

**Comment by nikolaglumac** [comment] 2021-09-08 07:52
Closing as this is a duplicate of https://github.com/input-output-hk/daedalus/issues/605
We have this item in our backlog and we will let you know as soon it gets scheduled for implementation.
This feature is very much needed and we will make sure to add it.
Thanks for the patience!

**Closed by nikolaglumac** 2021-09-08 07:52 UTC
