### ISSUE TITLE
Bug: daedalus does not show pool based on most recent registration and valid metadata

### ISSUE THREAD

**Issue by zenithpool** [input-output-hk/daedalus#2060] opened 2020-07-07 21:59 UTC
**Summary**
- If you create multiple pools with the same metadata URL. The intended pool will not show up Daedalus but will show in pooltool.

**Steps to reproduce**
1. Create the first pool with the ticker `ZEN`. 
2. Wait for one epoch.
3. Verify that the `ZEN` pool shows up in Daedalus. Evidence in [Rick's Tweet](https://twitter.com/RichardMcCrackn/status/1280067344962932736). 
4. Create another pool `ZENT` with new payload at the same metadata URL. 
5. Wait for one epoch.
6. Verify that the `ZENT` pool shows up in Daedalus. Refer to screenshot 1 below
7. Reregister first `ZEN` pool with new payload at same metadata URL. 
8. Wait for one epoch.
9. Verify that [Pooltool](https://htn.pooltool.io/pool/27234c8c0eef33c1c17575f0b4a074e4d65f98544adadf2741228a5b/blocks) show the correct metadata for `ZEN` pool. Refer to screenshot 2 below
10. Verify that metadata is valid for `ZEN` pool at pooltool. Refer to screenshot 2
11. Verify that meta shows incorrect metadata for `ZENT` pool. Refer to screenshot 3
12. Daedalus should show pool `ZEN` and not `ZENT` but does not.

**Screenshot 1**
![image](https://user-images.githubusercontent.com/56691430/86845777-9a3fd980-c06f-11ea-9355-e33d2b5faafb.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/56691430/86846892-138bfc00-c071-11ea-8311-404d4901db15.png)

**Screenshot 3**
![image](https://user-images.githubusercontent.com/56691430/86847006-4afaa880-c071-11ea-95ad-aad670a923fb.png)

**Comment by zenithpool** [comment] 2020-07-07 23:57
This is on a MacOS. 

After I deleted the daedalus app and removed the data with 
```
$ rm -rf /Users/<user-name>/Library/Application\ Support/Daedalus\ Shelley\ Testnet\ v2
``` 

I reinstalled the app, it now shows the correct pool. I am concerned that some caching issues are happening...

![image](https://user-images.githubusercontent.com/56691430/86857114-6a9acc80-c083-11ea-88d4-2c5e6da71bba.png)

**Comment by zenithpool** [comment] 2020-07-08 00:00
After checking with cardano-wallet and grabbing the pools at this current time. 3 pools show up with the same metadata URL at https://metadata.zenithpool.io/metadata/json. Daedalus may have only had one appear based on a certain check.

[stake_pool.txt](https://github.com/input-output-hk/daedalus/files/4887647/stake_pool.txt)

**Comment by nikolaglumac** [comment] 2021-02-03 13:32
Daedalus shows only pools that have been picked up by the SMASH server.
Please follow this thread for more info: https://github.com/input-output-hk/daedalus/issues/2117

Closing this issue now as it is a duplicate of the one I linked above...

**Closed by nikolaglumac** 2021-02-03 13:32 UTC
