### ISSUE TITLE
Wallet fails time sync and becomes unusable after sleep [Windows]

### ISSUE THREAD

**Issue by mikegogulski** [input-output-hk/daedalus#2145] opened 2020-08-10 18:40 UTC
# Context
 
When the host computer (Windows) emerges from sleep (or hibernate?) with the wallet running, it becomes unusable until restarted with this message:
![Annotation 2020-08-10 202904](https://user-images.githubusercontent.com/118625/89817587-b5a77400-db48-11ea-9923-29a032ec4705.png)

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.8.3 (git revision: d5b43356e4dbe9267ede9c8e912da6c893bdda85) |
| Platform     | Windows 10 Pro v1909 build 18363.959          |
| Installation | binary install from https://daedaluswallet.io/            |

# Steps to Reproduce

1. Launch Shelley wallet
1. Wait for checks/syncs to finish
1. Put computer to sleep
1. Awaken computer

## Expected behavior

Wallet resumes normal operation.

## Actual behavior
 
Wallet is locked up in an unusable state until restarted, displaying the error message in the screenshot above. Wallet can be restarted and then works fine, until the next sleep.

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment] 2020-08-11 06:26
Moving this to input-output/daedalus :+1: 

cc @nikolaglumac

**Comment by nikolaglumac** [comment] 2021-02-03 13:47
@gnpf @ManusMcCole @mioriohk can you please try to reproduce this on all 3 platforms and let us know the results 🙏

**Comment by gnpf** [comment] 2021-02-08 14:56
@nikolaglumac I couldn't reproduce the issue on macOS and I would add results for Linux soon.

On Windows, I have not encountered this issue, but Daedalus closes when the machine hibernates. Sometimes [this error](https://drive.google.com/file/d/1dGCGOmT-xrQhUgFef073kuPR8Xe_raIa/view?usp=sharing) is displayed after waking it. Check also [the logs](https://drive.google.com/file/d/1uQlCBHZP7Fkgy-Ow0UoRJt3UWjEHj31l/view?usp=sharing).

This was tested on 3.2.0.

**Comment by nikolaglumac** [comment] 2021-02-11 16:58
Thanks @gnpf - what you have found is a different issue.
I am closing this one since the originally reported issue can not be reproduced.

**Closed by nikolaglumac** 2021-02-11 16:58 UTC
Labels: bug
