### ISSUE TITLE
Ledger pair error occurred  

### ISSUE THREAD

**Issue by v21vicky** [input-output-hk/daedalus#2382] opened 2021-02-18 12:51 UTC
hi all first time on gate hub means i need help please. i was using daedalus wallet with ledger and everything works fine till we had latest update 3.0.0 after that i had problem with connecting to network. i uninstall and install wallet again. but now i can't pair my ledger keep saying error occurred. my all device up to date cardano app up to date. im using ledger with passphrase. on 24 seed i can pair but with 25th word passphrase seed i can't error occurred anyone please if can solve this issue.

**Comment by nikolaglumac** [comment] 2021-02-18 16:47
Thanks for submitting the ticket. We will investigate and get back to you!

**Comment by nikolaglumac** [comment] 2021-03-16 09:23
@v21vicky we were unable to reproduce the issue. I believe it was something temporary and you should not see the problem if you update to the latest version oo Daedalus.
Please do that and let us know if it is working fine now. Thanks!

**Comment by nikolaglumac** [comment] 2021-03-22 19:21
Closing this one since we can not reproduce it and I hope neither can you @v21vicky 🙏

**Closed by nikolaglumac** 2021-03-22 19:21 UTC
Labels: bug
