### ISSUE TITLE
Odd withdrawal fee >1Ada when withdrawing staking rewards

### ISSUE THREAD

**Issue by katakombi** [input-output-hk/daedalus#2368] opened 2021-02-17 04:42 UTC
Hi,

 I recently wanted to withdraw my staking rewards from my main wallet when I noticed that the withdrawal fee was more than 1.17 Ada. First I almost couldn't believe it and lowered it by 1 Ada, and the fee was around 0.18. Also when I raised it by 1 Ada, fee was again something like 0.18. I tried to figure out the "boundaries" but I couldn't get a clue about what was happening.

I really found it odd that this just happened when I wanted to withdraw exactly the amount that I just obtained as staking reward. I never have seen a withdrawal fee of 1 Ada or more before.

Is it a bug?

**Comment by rdlrt** [comment] 2021-02-17 04:45
Assuming you had some transactions between 1.17 and 0.18 ADA as fee, You might want to check the example mentioned [here](https://iohk.zendesk.com/hc/en-us/articles/900001987323-Fees-Explained) as part of explanation for how fees work

**Comment by katakombi** [comment] 2021-02-17 04:51
Ah, didn't know this can happen. I thought it is a linear function (sth like a+b*amount). Can it be related to the rewards amount or was it just coincidence?

**Comment by rdlrt** [comment] 2021-02-17 05:36
The amount of rewards you have does not have an impact on transaction fee. It would be affected by how your funds are distributed in _non-reward part_ of your balance.
Yes, the transaction fees are `a+b*(size in bytes)` but as explained in link there is also minUtxoValue which is 1 ADA. If you had a single input of 1 ADA and you're paying 0.18 ADA as transaction fee, the left over change that goes to new address is 0.82 ADA which is less than the minimum UTXO that can be created (which is 1 ADA)

**Comment by nikolaglumac** [comment] 2021-02-17 08:37
Hi @katakombi and @rdlrt!

The cause of this behavior is in random input selection and minimum UTXO value.
It has nothing to do with the size of your rewards...

Every transaction in Daedalus passes two phases:
1) Fee estimation
2) Transaction submission.

Both of these include running random input selection on the cardano-wallet side.
In order to estimate fees, cardano-wallet runs a few of the random input selections and returns a range of potential fees.
Daedalus always shows the highest number in this range as the potential fee.
Then once you submit the transaction this same random input selection is run again, and it generates the final transaction which may or may not be the same one as the one (in terms of the inputs that got selected) as the one used in fee estimation step. Thus the final fees might be different than the ones you saw estimated before you made the transaction.
Usually, expected fees are around ~0.17 ADA, however, it could happen that you have a lot of small UTXOs in your wallet (ones close to minimum UTXO of 1 ADA), and in the case of cardano-wallet randomly picking such a UTXO, it can not return you the change which would be less than minimum UTXO value and then this extra amount is (unfortunately) turned into fees.

So if you have a UTXO of 1.17 ADA and that one gets selected to pay for the withdrawal fees, it will all be used for the fees as 1.17 ADA minus ~0.17 ADA fee would be most likely less than minimum UTXO of 1 ADA.

This is how the cardano-wallet works and there is nothing we can do on our end.
However, the improvement we can all look forward to is the change where we'll get the actual transaction (unsigned) in the fee estimation and we will be able to show you the exact inputs used and the fixed fee which won't change after you submit the transaction. This should be implemented on cardano-wallet side after Mary hard fork.

I will now close this issue as this (unfortunate) behavior is expected and not a bug.

Thanks!

**Closed** 2021-02-17 08:37 UTC
Labels: question
