### ISSUE TITLE
How to set the block storage location?

### ISSUE THREAD

**Issue by ye21st** [input-output-hk/daedalus#1150] opened 2018-10-30 05:15 UTC
I want to know how to set the storage location of the wallet sync data. The default is to sync to the C drive. However, if I want to sync it to the D drive or the mobile hard drive, is there a way to set it?

**Comment by nikolaglumac** [comment] 2019-01-30 10:19
Duplicate of: https://github.com/input-output-hk/daedalus/issues/605

**Closed by nikolaglumac** 2019-01-30 10:19 UTC
