### ISSUE TITLE
Sending Tokens doubles the Amount of ADA and Tokens???

### ISSUE THREAD

**Issue by rx2347** [input-output-hk/daedalus#2728] opened 2021-10-29 15:20 UTC
After sending ONE Token, I get two new entries in the ledger, one "Multiple tokens sent" (thats just a typo, if its 1 token, it should not say MULTIPLE) and another pending transaction. The amount of ADA in the wallet and all token counts have DOUBLED...

I have to quit Daedalus und restart, cancel the pending transaction to get everything working again. Quite frightening, pls fix asap...

This is on 4.4.1 on Mac OS Big Sur

![Screenshot 2021-10-29 at 17 16 46](https://user-images.githubusercontent.com/16007025/139460574-66840321-9815-4367-938d-de34f9f55244.png)
.

**Comment by dmitrii-gaico** [comment] 2021-12-09 11:13
Closing the card due to no details were provided and our was not able to reproduce the issue. @rx2347 Please create a new card if you still facing the issue.
Thank you!

**Closed by dmitrii-gaico** 2021-12-09 11:13 UTC
Labels: question
