### ISSUE TITLE
Strong interaction with Win10 Antimalware Service Executable - Windows Defender Antivirus Service

### ISSUE THREAD

**Issue by c0ndensate** [input-output-hk/daedalus#618] opened 2017-12-21 19:54 UTC
I noticed a very strong interaction between Daedalus and Antimalware Service Executable - Windows Defender Antivirus Service on my freshly installed / fully updated instance of Windows 10 Pro x64. I had let the computer "settle" for a 3 hours before installing and running Daedalus for the first time.

The interaction is *especially* strong (and possibly of great nuisance causing slowness) when restoring wallet from backup (using the 12 word recovery phrase).

It may be that disabling Real-time protection in "Virus & threat protection settings" during heavy cpu/io-bound tasks greatly improves task completion times.

The attached screenshot does not represent the worst case of the interaction, which was during the "restore wallet from backup". The attached screenshot was taken during the sync when launching Daedalus merely to provide context to this issue.

![image](https://user-images.githubusercontent.com/29126769/34272177-512fddb0-e65d-11e7-8024-147d26514096.png)

**Comment by neongreen** [comment] 2017-12-22 00:27
We're not sure but we suspect that this is a side-effect of our block storage mechanism (lots and lots of small files). I'm currently writing a proposal on an alternative way to store blocks, so there's a good chance that this issue will be fixed in one of the next releases, if your problem is indeed caused by that.

Can you look at the Windows Defender process in [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and check what it does when it eats 30% of CPU? (If it accesses blocks, you'll see lots of accesses to files with hashes as names)

**Comment by c0ndensate** [comment] 2017-12-22 04:38
This was also my initial feeling re lots of small files.

I will get you the process monitor results next week.

**Comment by c0ndensate** [comment] 2017-12-22 18:51
I had some time today and obtained some results using Process Monitor

There are two (2) traces :1) with Defender ON, and 2) with Defender OFF. For each test, I restored using the same 12 word recovery phrase. Refer to the screenshot to see where I changed this setting.

The wallet restore took 35 minutes with Defender ON and only 12 minutes with Defender OFF. That's a 65% reduction in time to complete the wallet restore task with Defender OFF. The difference in block time/height between the two trials is less than an hour apart or less than 1%. I restarted Daedalus between trials. I did not restart the computer however.

For each test, I ran process monitor with /NoConnect and the moment I started the restore function in Daedalus I did Ctrl+E in process monitor to begin recording. When the wallet restore task finished in Daedalus, I let process monitor run for 20 additional seconds before I stopped recording.

The Windows Defender / antimalware service executable corresponds to MsMpEng.exe

1) Defender ON trace results :

Process Name Count
"Value","Count"
"cardano-node.exe","171964"      <-------
"csrss.exe","12"
"Daedalus.exe","9927"
"Explorer.EXE","52"
"lsass.exe","100"
"MsMpEng.exe","40010"               <-------
"NVDisplay.Container.exe","2105"
"OfficeClickToRun.exe","8"
"OneDrive.exe","8"
"RuntimeBroker.exe","2"
"SearchFilterHost.exe","3"
"SearchIndexer.exe","95"
"SearchProtocolHost.exe","3"
"services.exe","1"
"svchost.exe","4017"
"wmiprvse.exe","1559"

Stack Summary
![defenderon_stacksummary](https://user-images.githubusercontent.com/29126769/34308855-35ee6d9e-e71d-11e7-8ac3-918ccafde105.PNG)

Process Activity Summary
![defenderon_processactivitysummary](https://user-images.githubusercontent.com/29126769/34308866-3bea2ed6-e71d-11e7-8609-21bdfe43b7cd.PNG)

Random Screenshot 1
![defenderon_randomscreenshot1](https://user-images.githubusercontent.com/29126769/34308871-40d51a78-e71d-11e7-959e-5c855665f65c.PNG)

Random Screenshot 2
![defenderon_randomscreenshot2](https://user-images.githubusercontent.com/29126769/34308878-44aa64c8-e71d-11e7-80d5-9cdac0b3e596.PNG)

Random Screenshot 3
![defenderon_randomscreenshot3](https://user-images.githubusercontent.com/29126769/34308880-46cb0cee-e71d-11e7-9981-02491b9d6534.PNG)

Random Screenshot 4
![defenderon_randomscreenshot4](https://user-images.githubusercontent.com/29126769/34308884-4a2da28e-e71d-11e7-8245-4a1dd104689a.PNG)

Random Screenshot 5
![defenderon_randomscreenshot5](https://user-images.githubusercontent.com/29126769/34308886-4c46840a-e71d-11e7-9d96-ea39bc955adc.PNG)

2) Defender OFF trace results :

Process Name Count
"Value","Count"
"cardano-node.exe","8930032"    <-------  (not sure why the count is much higher during this trial)
"Daedalus.exe","136699"            (not sure why the count is much higher during this trial)
"svchost.exe","47812"                 (not sure why the count is much higher during this trial)
"NVDisplay.Container.exe","11043"
"wmiprvse.exe","3157"
"taskhostw.exe","1872"
"SearchIndexer.exe","1274"
"sihclient.exe","1117"
"smartscreen.exe","969"
"services.exe","714"
"conhost.exe","572"
"SecurityHealthService.exe","545"
"Explorer.EXE","420"
"MsMpEng.exe","306"                  <-------  (much less count!!!)
"lsass.exe","286"
"OfficeClickToRun.exe","124"
"dwm.exe","105"
"OneDrive.exe","104"
"winlogon.exe","93"
"csrss.exe","62"
"sihost.exe","62"
"DllHost.exe","61"
"AUDIODG.EXE","56"
"RuntimeBroker.exe","21"
"ApplicationFrameHost.exe","8"
"cardano-launcher.exe","2"
"smss.exe","1"

Stack Summary
![defenderoff_stacksummary](https://user-images.githubusercontent.com/29126769/34309131-7bdf1d7a-e71e-11e7-9232-600beeed6312.PNG)

Process Activity Summary
![defenderoff_processactivitysummary](https://user-images.githubusercontent.com/29126769/34309137-8370cd40-e71e-11e7-9763-48a121bcba6d.PNG)

Random Screenshot 1
![defenderoff_randomscreenshot1](https://user-images.githubusercontent.com/29126769/34309152-9306892a-e71e-11e7-9250-089e19fb85b3.PNG)

Random Screenshot 2
![defenderoff_randomscreenshot2](https://user-images.githubusercontent.com/29126769/34309153-954d9200-e71e-11e7-81e8-52a331dab139.PNG)

Random Screenshot 3
![defenderoff_randomscreenshot3](https://user-images.githubusercontent.com/29126769/34309155-974057f0-e71e-11e7-9a3d-31656fc232d4.PNG)

Random Screenshot 4
![defenderoff_randomscreenshot4](https://user-images.githubusercontent.com/29126769/34309158-99354200-e71e-11e7-8452-015d7325078f.PNG)

Random Screenshot 5
![defenderoff_randomscreenshot5](https://user-images.githubusercontent.com/29126769/34309160-9b0da4d2-e71e-11e7-9e6e-c39ba3b5f85f.PNG)


I find it strange that there is a much higher count during the Defender OFF trial for cardano-node.exe, Daedalus.exe, and svchost.exe

If you want, I can reboot the machine and do another Defender OFF trial.

**Comment by c0ndensate** [comment] 2017-12-22 19:01
FYI, my system details. As I mentioned already, this is a fresh instance of Windows. I have only installed Daedalus, Chrome, Office 2013, and Visual Studio Community 2017 (desktop, mobile, and azure development components). All updates were done and made sure that computer was settled. 

![systemdetails](https://user-images.githubusercontent.com/29126769/34309370-a8a5b9bc-e71f-11e7-8bba-119e6bae4572.PNG)

Also, here are the Defender Settings. Trial 1 was all three (3) highlighted switches ON and Trial 2 was all three (3) highlighted switches OFF.

![defender_settings](https://user-images.githubusercontent.com/29126769/34309548-971f3fdc-e720-11e7-86b9-522efadaaa10.PNG)

**Comment by nikolaglumac** [comment] 2019-01-30 14:15
These issues are resolved with the introduction of the blockchain storage consolidation which was released in Daedalus v0.12.0. Find out more about this process on the Support portal: https://iohk.zendesk.com/hc/en-us/articles/360016060314-Blockchain-storage-consolidation

**Closed by nikolaglumac** 2019-01-30 14:15 UTC

**Comment by galki** [comment] 2020-02-27 01:02
I'm on `0.15.1` and getting the same symptoms.

**Comment by nikolaglumac** [comment] 2020-03-02 08:15
Thanks for reporting this @galki!

@DmitriiGaico can we please have this checked?

cc @alan-mcnicholas

**Comment by nikolaglumac** [comment] 2020-03-03 10:55
@galki this is a known issue and indeed adding `cardano-node.exe` to an exclusion list and\or the state directory helps. The issue is most apparent when syncing Daedalus as the large numbers of disk I/O get scanned by Defender which slows things down as we are syncing the original chain and at the same time consolidating the blocks. Once consolidation happens the overhead of Windows Defender is much less.
