### ISSUE TITLE
FR: Daedalus should have a "de-register stake key" option

### ISSUE THREAD

**Issue by erikd** [input-output-hk/daedalus#2602] opened 2021-06-21 08:02 UTC
The `cardano-wallet` already supports this: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/quitStakePool so it is probably just a matter of hooking it up to the UI and testing.

**Comment by daniloprates** [comment] 2021-06-22 13:12
We have [this done](https://github.com/input-output-hk/daedalus/pull/2351), but currently [disabled](https://github.com/input-output-hk/daedalus/blob/develop/source/renderer/app/config/walletsConfig.js#L46). I'll discuss it with @darko-mijic, when he is back.

**Comment by nikolaglumac** [comment] 2021-07-04 11:02
Closing this ticket as it is a duplicate of: https://github.com/input-output-hk/daedalus/issues/2367

**Closed by nikolaglumac** 2021-07-04 11:02 UTC
Labels: feature-request
