### ISSUE TITLE
Crash when saving PDF (Registration to vote for Fund3)

### ISSUE THREAD

**Issue by FelixTruger** [input-output-hk/daedalus#2414] opened 2021-02-27 23:23 UTC
My Daedalus 3.3.1 crashed when I tried to save the PDF of the QR code created in the Registration menu for Fund3. I scanned the code using the Catalyst App before. When I clicked the Save PDF button, Daedalus completely vanished from the screen without any trace or error message.

You may want to double check that exception handling is done correctly there.

I'm using Ubuntu 18.04.4 LTS in case that's relevant. I would provide relevant logs if I knew where to find them. Just kindly let me know if you need more info.

**Comment by nikolaglumac** [comment] 2021-03-01 14:09
@gabriela-ponce @miorsufianiohk @ManusMcCole please check this 🙏

**Comment by gabriela-ponce** [comment] 2021-03-02 23:12
@nikolaglumac I can't reproduce this scenario in Mainnet, but I tried to download the rest of the PDF and other files in Daedalus and it worked as expected.

**Comment by nikolaglumac** [comment] 2021-03-03 09:26
@gabriela-ponce did you test it on the same Ubuntu version @FelixTruger is using?

**Comment by ManusMcCole** [comment] 2021-03-03 09:54
Im taking a look now on an 18.04 Ubuntu VM that I have @nikolaglumac

**Comment by gabriela-ponce** [comment] 2021-03-03 11:20
@nikolaglumac Yes, Ubuntu 18.04 (VM)

**Comment by nikolaglumac** [comment] 2021-03-03 11:21
@FelixTruger do you have some special config on your platform?

**Comment by ManusMcCole** [comment] 2021-03-03 11:32
My chain folder transplant kept not working correctly. Syncing chain from scratch 🐢 but I will post results when its done. Im trying on 18.04 also

**Comment by FelixTruger** [comment] 2021-03-03 17:45
> @FelixTruger do you have some special config on your platform?

To be more precise, I was using Lubuntu (i.e., LXDE). But I guess it was just a sporadic error. In the meantime, I tried again to save the PDF (after rebooting) which worked just fine. I don't think this will be reproducable. I just meant to inform you that it seemed like there was missing exception handling in this crucial step.

Thanks everyone for checking it out, 

Kind regards

**Comment by nikolaglumac** [comment] 2021-03-03 17:49
Thanks for letting us know @FelixTruger!
Glad it is working for you now.
Closing this issue...

**Closed by nikolaglumac** 2021-03-03 17:49 UTC
Labels: bug
