### ISSUE TITLE
Stake pool popup errors and ranking issue

### ISSUE THREAD

**Issue by bobdobs** [input-output-hk/daedalus#1846] opened 2020-02-11 11:08 UTC
Running Daedalus v2.0.1 ITN-1

My pool ticker is ADAGE. It has produced two out of two possible blocks: 
https://shelleyexplorer.cardano.org/block/8aa739cba7ce22d16bc4e4639ff36e97939bf9aacab6a1d600d1864c91f628d4
https://shelleyexplorer.cardano.org/block/34515364225c3f628ebab2f3613b11328590fd8ec7a0be3a9af7a8f76a438705
...but according to popup in Daedalus it has produced 0. 

Before I produced my first block my rating was around 480. Right after my pool produced the first block the ranking increased to 245. Yay! Rankings dropped around 10 places before I got my next block. But right after I got the second block my rating dropped to 460. 

When I produce blocks for 100% of the slots assigned to my pool, I expect a better (not worse) ranking in Daedalus :-)

Finally the popup states the my pool fee is 3% but it is 3.4%.

**Comment by Straightpool** [comment] 2020-02-12 08:52
This is a known issue because of a limitation of Jormungandr, see https://github.com/input-output-hk/cardano-wallet/issues/1335 and https://github.com/input-output-hk/jormungandr/issues/852

Please do upvote the later criticial root cause!

In all cases I have looked at when ranking does not match reality the stake-pools.sqlite db is incomplete and lacking epochs which would increase ranking. This is a major problem for small pools alas, big pools which regular blocks per epoch do not care.

You can easily query your own Daedalus sqlite.db, see the above tickets. You can find the state directory where the DB is stored via Daedalus diagnostics.

Deadalus rounds pool fee to a single digit, which is why 3.4% is displayed as 3%, Same for e.g. EPIC which has 4.9%, rounded to 5% in Daedalus.

**Comment by nikolaglumac** [comment] 2020-02-28 13:20
As @Straightpool stated, there is nothing we can do on Daedalus side to improve this situation.
This is why in the latest version we have introduced the "Experimental data" notification: https://iohk.zendesk.com/hc/en-us/articles/900000241823

**Comment by Straightpool** [comment] 2020-02-28 14:11
Are there any plans to tackle the underlying issue in Jormungandr so the feature is no longer experimental/broken for most users? Would love to see the ticker https://github.com/input-output-hk/jormungandr/issues/852 get assigned to get more attention.
Thanks for the hard work!

**Comment by nikolaglumac** [comment] 2020-03-02 07:57
@Straightpool I suggest you post this question directly on the Jormungandr issue.

**Closed** 2020-05-06 20:22 UTC
