### ISSUE TITLE
Let the end user know that there is a 2.174521 ada fee when entering pool

### ISSUE THREAD

**Issue by chsami** [input-output-hk/daedalus#2344] opened 2021-02-06 15:45 UTC
I'm a new user to daedalus and experimenting with it...One thing I found confusing was the 2.174521 ada fee...

Let the user know that there is a 2.174521 ada fee when entering pool. And that we recover this when we exit the pool.

![image](https://user-images.githubusercontent.com/23292806/107122811-495cc180-689a-11eb-9db5-598e8b08fbf4.png)

It was very confusing to see -2.174521 ada substracted from my wallet with no consent or information anywhere on the screen.

**Comment by nikolaglumac** [comment] 2021-02-06 15:55
Closing this ticket as it is a duplicate of https://github.com/input-output-hk/daedalus/issues/2116

Please see the details on the link above.

**Closed by nikolaglumac** 2021-02-06 15:55 UTC
