### ISSUE TITLE
how to build wallet on linux

### ISSUE THREAD

**Issue by HaleDennis** [input-output-hk/daedalus#712] opened 2018-02-06 08:36 UTC
How to build wallet on linux

**Comment by cleverca22** [comment] 2018-02-12 07:53
duplicate of #631

**Comment by cleverca22** [comment] 2018-02-12 07:56
also, try using `nix-env -f release.nix -iA daedalus` on the devops-13 branch, after you have installed [nix](https://nixos.org/nix/download.html)

**Comment by domenkozar** [comment] 2018-02-14 14:24
Merging into #492

**Closed by domenkozar** 2018-02-14 14:24 UTC
