### ISSUE TITLE
Daedalus breaks when reaching a high amount of tx/tokens.

### ISSUE THREAD

**Issue by ruttydm** [input-output-hk/daedalus#2583] opened 2021-06-03 14:44 UTC
I just minted 1,3k tokens (NFT's) into my daedalus wallet. But now Daedalus has became unusable and I can't even delete the wallet anymore. Only way for me to get daedalus working is through deleting the wallet from the file explorer.

Multiple users on the CardanoNFT discord server report the same problem. Daedalus exponentially slows down with the number of tokens/transactions to he point it's unusable.

**Comment by matiwinnetou** [comment] 2021-06-03 19:50
This fixes it: https://github.com/input-output-hk/cardano-wallet/pull/2676, maybe this was even released with today's Daedalus 4.1.0.

**Comment by ruttydm** [comment] 2021-06-03 20:06
> This fixes it: [input-output-hk/cardano-wallet#2676](https://github.com/input-output-hk/cardano-wallet/pull/2676), maybe this was even released with today's Daedalus 4.1.0.

I see, the 4,1 version still has the same issue. But I will try out the flight version now.

**Comment by nikolaglumac** [comment] 2021-06-04 05:57
> > This fixes it: [input-output-hk/cardano-wallet#2676](https://github.com/input-output-hk/cardano-wallet/pull/2676), maybe this was even released with today's Daedalus 4.1.0.
> 
> I see, the 4,1 version still has the same issue. But I will try out the flight version now.

https://github.com/input-output-hk/cardano-wallet/pull/2676 is was not released in cardano-wallet [`v2021-05-26`](https://github.com/input-output-hk/cardano-wallet/tree/v2021-05-26) which is used in Daedalus Mainnet 4.1.0 and Daedalus Flight 4.1.0-FC1 so this issue unfortunately still persists... 

Closing this ticket as it is a duplicate of https://github.com/input-output-hk/daedalus/issues/2487

**Closed by nikolaglumac** 2021-06-04 05:57 UTC
