### ISSUE TITLE
Change storage location

### ISSUE THREAD

**Issue by benapetr** [input-output-hk/daedalus#2412] opened 2021-02-27 20:09 UTC
Hello,

The program doesn't seem to have any option to change storage location, I have NVME disk I would like to move the DB to, so that blockchain scanning is faster and app doesn't take forever to start, but there is no option in preferences to change where you want to store it. Defaults to somewhere in AppData on system disk.

**Comment by nikolaglumac** [comment] 2021-02-27 23:15
Closing this ticket as it is a duplicate of: https://github.com/input-output-hk/daedalus/issues/605
Please follow these steps: https://github.com/input-output-hk/daedalus/issues/605#issuecomment-771782614

**Closed by nikolaglumac** 2021-02-27 23:15 UTC
