### ISSUE TITLE
Windows: add ability to choose data folder during installation

### ISSUE THREAD

**Issue by bjendyk** [input-output-hk/daedalus#595] opened 2017-12-17 17:45 UTC
Currently, the downloaded blockchain and logs reside in the %APPDATA% folder, which defaults to C:\Users\<username>\AppData\Roaming. While this can be changed at system level (using registry editor for example), not many people are aware of this.

Therefore an option asking the user for the data folder location during installation would be very welcome. Inexperienced users will end up with their C: partition clogged with Daedalus data, especially when the file system on that partition uses default block size (huge amount of small files * default, not minimal file size === significantly larger disk space usage than the files' real weight). Most users don't pay attention how the partition is formatted.

**Comment by nikolaglumac** [comment] 2019-01-30 11:02
Duplicate of: https://github.com/input-output-hk/daedalus/issues/605

**Closed by nikolaglumac** 2019-01-30 11:02 UTC
