### ISSUE TITLE
Import Wallet Via Daedalus State Directory and Secret.Key File but no ADA in it (#2507)

### ISSUE THREAD

**Issue by olafeyikan** [input-output-hk/daedalus#2511] opened 2021-04-08 11:48 UTC
Hello again support team:

If I have 2 wallets on the same Daedalus application does that mean I will have 2 Daedalus State Directory or Secret.key files? this is what happened to me, I created 2 wallets on the same Daedalus Application running on my desktop. today I import wallet and can only see the primary wallet and its transaction details, I can not see the other transaction from the other wallet.

Is this normal?

**Comment by nikolaglumac** [comment] 2021-04-12 08:39
Closing as this is a duplicate of https://github.com/input-output-hk/daedalus/issues/2507

**Closed by nikolaglumac** 2021-04-12 08:39 UTC
