### ISSUE TITLE
Wallet stuck on loading screen at 0% "Verifying the blockchain"

### ISSUE THREAD

**Issue by geektechniquestudios** [input-output-hk/daedalus#2514] opened 2021-04-09 01:13 UTC
![image](https://user-images.githubusercontent.com/42378648/114114015-e98c9200-98ad-11eb-8dfe-7151eb1f4608.png)
[logs-2021-04-09T010332.0235Z.zip](https://github.com/input-output-hk/daedalus/files/6282472/logs-2021-04-09T010332.0235Z.zip)

This is not the first time I've encountered this issue. I've waited several hours for this process to progress, but nothing has happened. Restarting my machine did not work. My internet connection is very stable and high bandwidth, and my computer has a lot of excess resources. This problem is almost definitely not the result of something physical failing.

I'm using a fresh install of Ubuntu 20.04.2. I have also experienced this same issue on a different physical machine. The only solution for me is to completely uninstall the wallet, reinstall, resync, and reload from a recovery phrase. This poses a great usability issue as well as requires significant effort from the user; it takes almost an hour to access my ADA if I would like.

This issue is difficult to reproduce but is consistent enough for me to expect the same thing to happen in the future. If you need any additional details or would like help solving this bug, please lmk.

**Comment by buttery-potato** [comment] 2021-04-11 17:41
I am getting this issue as well.

**Comment by nikolaglumac** [comment] 2021-04-12 09:02
Please leave Daedalus running and it should eventually connect.
The cardano-node sometimes need up to 20-60 mins to boot.
The team is working on improving this.

Please let us know if leaving Daedalus running helps. Thanks!

**Comment by buttery-potato** [comment] 2021-04-12 16:13
I had Daedalus running all night (12 hrs) and still nothing.

**Comment by nikolaglumac** [comment] 2021-04-12 16:32
Please send the logs to nikola.glumac@iohk.io and I will check it out. Thanks!

**Comment by buttery-potato** [comment] 2021-04-12 17:28
Yes, it's synced.

**Comment by nikolaglumac** [comment] 2021-04-13 09:58
Node logs are full of these lines:

```
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:46][0m [2021-04-12 17:34:15.16 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:46][0m [2021-04-12 17:34:36.19 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
[33m[DESKTOP-:cardano.node.DnsSubscription:Warning:46][0m [2021-04-12 17:34:57.21 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Failed to start all required subscriptions
```

...while cardano-wallet ones have these ones repeating over and over again:

```
[34m[cardano-wallet.api-server:Info:103][0m [2021-04-12 17:35:10.90 UTC] [RequestId 100607] [GET] /v2/network/parameters
[34m[cardano-wallet.api-server:Info:90][0m [2021-04-12 17:35:10.90 UTC] [RequestId 100606] 200 OK in 0.001001s
[34m[cardano-wallet.api-server:Info:103][0m [2021-04-12 17:35:10.90 UTC] [RequestId 100607] 200 OK in 0s
[34m[cardano-wallet.api-server:Info:77][0m [2021-04-12 17:35:11.90 UTC] [RequestId 100608] [GET] /v2/network/parameters
[34m[cardano-wallet.api-server:Info:77][0m [2021-04-12 17:35:11.90 UTC] [RequestId 100608] 200 OK in 0s
[34m[cardano-wallet.api-server:Info:90][0m [2021-04-12 17:35:12.90 UTC] [RequestId 100609] [GET] /v2/network/information
[35m[cardano-wallet.network:Notice:90][0m [2021-04-12 17:35:12.90 UTC] Time interpreter queried past the horizon. 
Called from:
"src/Cardano/Wallet/Shelley/Api/Server.hs:447:9 in cardano-wallet-2021.3.4-AlzsuOp7qWXDfrMX5pZNr6:Cardano.Wallet.Shelley.Api.Server"
Converting expression:
Some (ELet (ERelTimeToSlot (EAbsToRelTime (ELit (RelativeTime 112045821.9029201s)))) (\x0 -> ELet (ERelToAbsSlot (EVar x0)) (\x1 -> EPair (ESnd (EVar x0)) (EPair (EVar x1) (ESlotLength (EVar x1))))))

With knowledge about the following eras:
    - EpochNo 0 to EpochNo 1

t0 = StartTime 2017-09-23 21:44:51 UTC
[34m[cardano-wallet.api-server:Info:103][0m [2021-04-12 17:35:12.90 UTC] [RequestId 100610] [GET] /v2/network/parameters
[34m[cardano-wallet.api-server:Info:90][0m [2021-04-12 17:35:12.90 UTC] [RequestId 100609] 200 OK in 0s
[34m[cardano-wallet.api-server:Info:103][0m [2021-04-12 17:35:12.90 UTC] [RequestId 100610] 200 OK in 0s
[34m[cardano-wallet.api-server:Info:77][0m [2021-04-12 17:35:13.90 UTC] [RequestId 100611] [GET] /v2/network/parameters
[34m[cardano-wallet.api-server:Info:77][0m [2021-04-12 17:35:13.90 UTC] [RequestId 100611] 200 OK in 0s
[34m[cardano-wallet.api-server:Info:90][0m [2021-04-12 17:35:14.90 UTC] [RequestId 100612] [GET] /v2/network/information
[35m[cardano-wallet.network:Notice:90][0m [2021-04-12 17:35:14.90 UTC] Time interpreter queried past the horizon. 
Called from:
"src/Cardano/Wallet/Shelley/Api/Server.hs:447:9 in cardano-wallet-2021.3.4-AlzsuOp7qWXDfrMX5pZNr6:Cardano.Wallet.Shelley.Api.Server"
Converting expression:
Some (ELet (ERelTimeToSlot (EAbsToRelTime (ELit (RelativeTime 112045823.9037392s)))) (\x0 -> ELet (ERelToAbsSlot (EVar x0)) (\x1 -> EPair (ESnd (EVar x0)) (EPair (EVar x1) (ESlotLength (EVar x1))))))

With knowledge about the following eras:
    - EpochNo 0 to EpochNo 1

t0 = StartTime 2017-09-23 21:44:51 UTC
[34m[cardano-wallet.api-server:Info:90][0m [2021-04-12 17:35:14.90 UTC] [RequestId 100612] 200 OK in 0s
[34m[cardano-wallet.api-server:Info:103][0m [2021-04-12 17:35:14.90 UTC] [RequestId 100613] [GET] /v2/network/parameters
[34m[cardano-wallet.api-server:Info:103][0m [2021-04-12 17:35:14.90 UTC] [RequestId 100613] 200 OK in 0s
```

Your machine clock looks good - there is less than a second drift.

@dcoutts @rvl @KtorZ any chance you could have a look into this?
I can share you the logs if needed.

**Comment by rvl** [comment] 2021-04-13 10:02
Thanks @nikolaglumac - we'll look into it.

**Comment by Anviking** [comment] 2021-04-13 12:54
### logs-2021-`04-09`T010332.0235Z.zip

I think the node is still replaying blocks here. It seems to be at 2021/04/02 13:41:44 UTC, judging from the last `Replayed block: slot SlotNo 25804613` message, despite the date being 04-09.

The wallet was last seen logging
```
[33m[cardano-wallet.network:Warning:30][0m [2021-04-09 01:03:34.95 UTC] Couldn't connect to node (x184). Retrying in a bit...
```

It looks like the wallet/node was running
- 23:08:28.12 - 23:36:24.71
- 00:57:35.68 - 01:03:35.04

with a few shutdowns.

Although the progress looks weirdly slow, I guess? (cc @dcoutts ?)

- [cardano.node.ChainDB:Info:21][2021-04-08 23:08:54.58 UTC] Replayed block: slot SlotNo 25784409 of At (SlotNo 25804613)
    - Slot corresponds to **2021/04/02 08:05:00_UTC**
- [cardano.node.ChainDB:Info:21][2021-04-08 23:08:55.73 UTC] Replayed block: slot SlotNo 25790359 of At (SlotNo 25804613)
- [cardano.node.ChainDB:Info:21][2021-04-08 23:08:55.73 UTC] Replayed block: slot SlotNo 25790377 of At (SlotNo 25804613)
- [cardano.node.ChainDB:Info:21][2021-04-08 23:08:58.81 UTC] Replayed block: slot SlotNo 25804613 of At (SlotNo 25804613)
- [cardano.node.ChainDB:Info:21][2021-04-09 01:03:11.03 UTC] Replayed block: slot SlotNo 25784409 of A****t (SlotNo 25804613)
- [cardano.node.ChainDB:Info:21][2021-04-09 01:03:11.32 UTC] Replayed block: slot SlotNo 25790359 of At (SlotNo 25804613)
- [cardano.node.ChainDB:Info:21][2021-04-09 01:03:11.33 UTC] Replayed block: slot SlotNo 25790377 of At (SlotNo 25804613)
- [cardano.node.ChainDB:Info:21][2021-04-09 01:03:11.94 UTC] Replayed block: slot SlotNo 25804613 of At (SlotNo 25804613)
    - Slot corresponds to **2021/04/02 13:41:44_UTC**


### logs-2021-`04-12`T173510.0187Z (same as Nikola's comment above) 

Here it seems like the wallet is neither applying blocks nor trying to connect to the node, which is weird. The logs are merely from the GET /network/information endpoint and not interesting. I wonder if the wallet logged some error message long before that. But that has been rotated out, even from the full logs. (they seem to be from 9-17) And unfortunately we don't have any smarter log rotation yet.

<hr>

@geektechniquestudios @buttery-potato if you still are able to reproduce this, any chance you could start Daedalus, and leave it open for 0.5h-2h, but no more, and report the logs?

I'm guessing the wallet will stop logging `Couldn't connect to node` at some point, and am curious about what it logs immediately afterward. (E.g. maybe some error)

**Comment by buttery-potato** [comment] 2021-04-13 15:48
[logs-2021-04-13T154640.0387Z.zip](https://github.com/input-output-hk/daedalus/files/6305002/logs-2021-04-13T154640.0387Z.zip)

**Comment by buttery-potato** [comment] 2021-04-13 23:57
Using a VPN fixes the problem.

**Comment by geektechniquestudios** [comment] 2021-04-14 06:33
> Using a VPN fixes the problem.

This issue just happened to me again, so I'll try this. I turned on a VPN after seeing your message and it jumped from 0 to 97.6% complete, where it currently sits. I'll post what happens when it moves again.

**Comment by nikolaglumac** [comment] 2021-04-14 07:10
@buttery-potato @geektechniquestudios were you able to use Daedalus without VPN before this "verification stuck at 0%" issue started to happen? 
If so, did you change your Internet connection provider? Can you please give us a bit more context?

**Comment by buttery-potato** [comment] 2021-04-14 15:35
Yes. I used Daedalus for a while but then this started 3 days ago. No change in ISP.

**Comment by geektechniquestudios** [comment] 2021-04-14 20:14
> @buttery-potato @geektechniquestudios were you able to use Daedalus without VPN before this "verification stuck at 0%" issue started to happen?
> If so, did you change your Internet connection provider? Can you please give us a bit more context?

I set up and started using the Daedalus wallet without a vpn a couple of months ago and did not have an issue. I have not changed my isp (google fiber).  The vpn I'm using is called Mullvad. I really haven't changed anything that I can think of.

**Comment by nikolaglumac** [comment] 2021-04-19 07:07
@buttery-potato @geektechniquestudios can you please try installing and running Daedalus 4.0.5 (https://daedaluswallet.io/en/download/) and let us know if you are still experiencing the same issues? 🙏 
Many thanks!

**Comment by buttery-potato** [comment] 2021-04-19 17:53
The new release works without a VPN. What do you think changed?

**Comment by geektechniquestudios** [comment] 2021-04-19 18:08
> @buttery-potato @geektechniquestudios can you please try installing and running Daedalus 4.0.5 (https://daedaluswallet.io/en/download/) and let us know if you are still experiencing the same issues? 🙏
> Many thanks!

As the issue is intermittent, it's hard to definitively say the problem is resolved. However, I haven't experienced the problem reported here since I updated.

I installed the update through a prompt in the wallet, as opposed to manually installing it. After doing that, it kept crashing and restarting, unable to sync. I restarted my system, and now everything seems to be working normally. I will report back if I have any problems.

**Comment by nikolaglumac** [comment] 2021-04-20 07:13
> The new release works without a VPN. What do you think changed?

We have [updated cardano-wallet revision](https://github.com/input-output-hk/daedalus/pull/2495) and [reduced the allowed NTP time drift](https://github.com/input-output-hk/daedalus/pull/2510) - these are the only changes I can see potentially fixing the issues you were experiencing.  I will close this ticket now since you can not reproduce the issue any longer.
Feel free to re-open it in case it happens again 🙏 
Thanks!

**Closed by nikolaglumac** 2021-04-20 07:13 UTC
Labels: question

**Comment by dessalines** [comment] 2021-09-14 17:26
I'm still getting this issue, even after a time sync.

**Comment by nikolaglumac** [comment] 2021-09-15 06:07
@dessalines it sometimes takes a long time for the node to start up. Sometimes up to 30 to 60 mins. Please let it run and see if it recovers. If not, then please let us know and provide the logs. Thanks!
