### ISSUE TITLE
Staking/voting rewards history

### ISSUE THREAD

**Issue by aljosa** [input-output-hk/daedalus#2410] opened 2021-02-26 11:48 UTC
Daedalus depends on cardano-wallet, where is the issue (in cardano-wallet or some other dependency you use) which is preventing detailed overview of staking/voting transactions?

I'd like to track the non-daedalus dependency that's blocking this.

**Comment by nikolaglumac** [comment] 2021-02-26 11:50
This is a duplicate of https://github.com/input-output-hk/daedalus/issues/2347
Please follow that thread instead. We are limited by the cardano-wallet API: https://github.com/input-output-hk/cardano-wallet

**Closed by nikolaglumac** 2021-02-26 11:50 UTC

**Comment by aljosa** [comment] 2021-02-26 12:50
@nikolaglumac there is no issue in cardano-wallet tracking this requirement?

**Comment by nikolaglumac** [comment] 2021-02-26 12:51
AFAIK it is only present in JIRA and not in GH.
