### ISSUE TITLE
Wallet crashes on Windows 10 

### ISSUE THREAD

**Issue by j2d3** [input-output-hk/daedalus#2591] opened 2021-06-07 19:57 UTC
Running 4.1.0 wallet on Windows 10 (windows insider latest build) - it crashes after some time. A few times I saw a message about an error, but I didn't screengrab. I think the error was memory related, and if I see it again, will grab it. Now, I am finding when I return to the computer after a few hrs having left the wallet running, the wallet app is closed (with no error message). I start it up again, and it syncs up and works fine. I downloaded the logs and went through them all, but there is no record of the crash / error in any of them. 

![wallet diag](https://user-images.githubusercontent.com/86860/121079686-4d88e500-c78f-11eb-995d-c7dc317832a7.png)

**Comment by nikolaglumac** [comment] 2021-06-08 08:01
@dmitrii-gaico please assist us here by trying to reproduce the issue 🙏

**Comment by dmitrii-gaico** [comment] 2021-06-09 07:42
@j2d3 Hello, thank you for your report. 
I was able to reproduce it. 
This issue would be investigated further. cc @nikolaglumac

**Comment by dmitrii-gaico** [comment] 2021-07-13 14:45
@j2d3 Hello. Would you be so kind and advise if you still experience the reported issue for the latest Daedalus version 4.2.0 ? From my side I can not longer reproduce the "Idle Crash" after updating to 4.2.0 version. I did kept Daedalus running overnight and it worked rock solid. Thank you in advance.
cc @nikolaglumac

**Comment by dmitrii-gaico** [comment] 2021-07-23 16:28
Closing the ticket as the issue is no longer reproducible. @j2d3 Please create a new ticket if you are still experiencing the issue so we can resume the research.

**Closed by dmitrii-gaico** 2021-07-23 16:28 UTC
Labels: bug
