### ISSUE TITLE
Multiple Wallets from a single Ledger

### ISSUE THREAD

**Issue by pabstma** [input-output-hk/daedalus#2357] opened 2021-02-11 13:30 UTC
Hi,

Ledger and Trezor both support the additional password feature, which makes it possible to generate multiple key pairs with the same seed but different passwords. This means that it is possible to have different wallets on the same ledger device.

Currently, it looks like Daedalus cannot manage multiple wallets that reside on the same hardware wallet. I only tested this with the Ledger Nano S and Nano X.

**Steps to reproduce:**
1. Initialize a Ledger hardware wallet with a standard 24 seed phrase + PIN.
2. In Daedalus click "Add wallet" and choose "Pair"
3. Follow the instructions to pair the Ledger
4. Disconnect the Ledger and set a temporary password, which creates a new set of keys
5. Repeat 2 & 3

**Expected behaviour:** 
A new wallet should be imported from the Ledger

**Actual behaviour:**
You will be forwarded to the view of the old wallet. It seems to recognize that you already paired this hardware wallet but it does not recognize that there is currently another wallet initialized.

This also leads to subsequent problems: e.g. You can try to send a transaction, you need to confirm it on the Ledger as always, but you'll get an error as soon as you are trying to send it, as the signature is from the wrong wallet (see attached picture).

![ledger_error](https://user-images.githubusercontent.com/29088060/107642529-4d5f5980-6c75-11eb-9304-fa5bc8a6d640.png)

**Comment by nikolaglumac** [comment] 2021-02-11 13:34
This is a known missing-feature and is to be implemented by: https://github.com/input-output-hk/daedalus/pull/2342 (at least for Ledger).

Trezor case is a bit different and we have it on our roadmap.
Also, this is a duplicate of: https://github.com/input-output-hk/daedalus/issues/2238

**Comment by nikolaglumac** [comment] 2021-02-11 13:36
This will be shipped in the upcoming Daedalus 3.3.0 release.
Thank you for your patience!

**Comment by nikolaglumac** [comment] 2021-02-17 20:20
The fix for this issue is now available in Daedalus Mainnet 3.3.0.
Please update your version of Daedalus either through the automatic update or manually by downloading the installer from: https://daedaluswallet.io/en/download/
Thank you for your patience!

**Closed by nikolaglumac** 2021-02-17 20:20 UTC
Labels: :airplane: release-3.3.0-FC1, feature-request, release-3.3.0
