### ISSUE TITLE
Hide slider until fully implemented

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/daedalus#2222] opened 2020-10-29 04:59 UTC
Using 220M as delegation amount in slider, the ranking is not reflecting the correct state (as 99.23% still shows up at rank 1, while it should be way lower. If a dependency is unavailable, please hide those components in UI.

![image](https://user-images.githubusercontent.com/3169068/97527496-90b3f600-19ff-11eb-90f0-7652b871326e.png)

**Comment by darko-mijic** [comment] 2020-10-29 10:49
This is due to our ranking system being non-myopic. It assumes optimal saturation of the pool. We are fully aware of this and our researchers are working on a hybrid myopic/non-myopic solution. 
The issue is not that severe since most of the delegators will not be delegating amounts of ada which will saturate a pool.

**Comment by rdlrt** [comment] 2020-10-29 14:03
> researchers are working on ..

Yes, included in issue description was hiding slider until fully functional.

> issue is not that severe since most of the delegators will not be delegating amounts of ada which will saturate a pool.

So expectation is an average delegator understands over saturation is. I can perhaps agree with that, but it certainly doesnt help us explain to SPOs/users about issue when asked multiple times from community management point of view, giving a bad UX 

I thought disabling a div temporarily by adding a flag wouldnt be a biggy, maybe not 😢

**Comment by darko-mijic** [comment] 2020-10-29 14:29
Actually, this improvement is already implemented and coming with the next update. We will be including a member stake in the calculation used by the stake pool ranking.

**Comment by darko-mijic** [comment] 2020-10-29 14:31
https://github.com/input-output-hk/cardano-ledger-specs/pull/1936

**Comment by Klobbinger** [comment] 2020-11-09 11:02
> This is due to our ranking system being non-myopic. It assumes optimal saturation of the pool. We are fully aware of this and our researchers are working on a hybrid myopic/non-myopic solution.

@darko-mijic : I hear this argument a lot, that this is due to the non-myopic ranking, but according to the specs the non-myopic stake is defined as `sigma_nm = max ((sigma + t, z0)` So if the current stake sigma plus intended user stake t are greater than z0, this value will be used fpr the non-myopic rewards calculation and thus reflecting the decreased member rewards due to over saturation. 

Another evidence the non-myopic member rewards calculation seems not to be correctly implemented in Daedalus is that there should be a significant cut in non-myopic member rewards between the top k pools and the rest, since for pools not in the top k the member rewards should be caluclated based on `sigma_nm = s + t`, pledge plus user stake. Since there is no significant cut (I haven't actually calculated this myself) it looks like z0 is used for all pools to calculate the non-myopic member rewards.

**Comment by rdlrt** [comment] 2020-12-06 22:21
> Actually, this improvement is already implemented and coming with the next update.

@darko-mijic 1.5 months and few releases later, I dont think we're any better wrt slider than when I raised the request. The slider does absolutely nothing useful atm whether I use 10 ADA to delegate or 10M, it still lists 99% saturated pools at the top (for 10M that's absolutely incorrect! )

**Comment by Klobbinger** [comment] 2020-12-11 21:55
It looks like you guys did it! I can finally sleep soundly again :) Thanks Darko et al!

**Comment by darko-mijic** [comment] 2020-12-12 13:30
Thank you!

**Closed by darko-mijic** 2020-12-12 13:30 UTC
